<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Xacro Properties -->
    <!-- TODO: Use correct dimensions -->
    <!-- Base dimensions -->
    <xacro:property name="base_length" value="0.5" />         <!-- Length of the base -->
    <xacro:property name="base_width" value="0.3" />          <!-- Width of the base -->
    <xacro:property name="base_height" value="0.2" />         <!-- Height of the base -->
    <xacro:property name="base_ground_clearance" value="0.1" /> <!-- Distance from ground to base
    bottom -->
    <!-- Wheel placement (symmetric) -->
    <xacro:property name="wheel_base" value="0.4" />          <!-- Distance between front and back wheels -->
    <xacro:property name="wheel_track" value="0.3" />         <!-- Distance between left and right wheels -->
    <!-- Wheel dimensions -->
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_thickness" value="0.05" />


    <!-- Base Link Definition -->
    <link name="base_link">
        <visual>
            <!-- Raise the base so its bottom is at ground clearance -->
            <origin xyz="0 0 ${base_ground_clearance + base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_ground_clearance + base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>
        <!-- Use box_inertia macro for base_link (mass = 10) -->
        <xacro:box_inertia m="10" w="${base_width}" h="${base_height}" d="${base_length}" />
    </link>


    <!-- Instantiate Four Wheels -->
    <!-- Front wheels: x_offset = +wheel_base/2, Rear wheels: x_offset = -wheel_base/2 -->
    <!-- Left wheels: y_offset = +wheel_track/2, Right wheels: y_offset = -wheel_track/2 -->
    <!-- z_offset is set to wheel_radius so that the wheel touches the ground -->
    <xacro:wheel name="front_left_wheel" x_offset="${wheel_base/2}" y_offset="${wheel_track/2}"
        z_offset="${wheel_radius}" is_right="false" />
    <xacro:wheel name="front_right_wheel" x_offset="${wheel_base/2}" y_offset="${-wheel_track/2}"
        z_offset="${wheel_radius}" is_right="true" />
    <xacro:wheel name="rear_left_wheel" x_offset="${-wheel_base/2}" y_offset="${wheel_track/2}"
        z_offset="${wheel_radius}" is_right="false" />
    <xacro:wheel name="rear_right_wheel" x_offset="${-wheel_base/2}" y_offset="${-wheel_track/2}"
        z_offset="${wheel_radius}" is_right="true" />

</robot>