joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear: # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 2.0

    axis_angular: # Right thumb stick horizontal
      yaw: 4
    scale_angular:
      yaw: 3.0
    scale_angular_turbo:
      yaw: 8.0

    require_enable_button: true
    enable_button: 4 # L1 button
    enable_turbo_button: 5 # R1 button

joy_control:
  ros__parameters:
    debug: false
