/twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel/key
        timeout: 0.5
        priority: 50

      joystick:
        topic: cmd_vel/joy
        timeout: 0.5
        priority: 125
