<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="vector">

    <!-- Lidar Link -->
    <link name="laser">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.01"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.01"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.01"/>
            </geometry>
        </collision>
    </link>

    <!-- Lidar Joint  -->
    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="0 0 ${(base_height/2 + 0.005)}" rpy="0 0 0"/>
    </joint>

    <!-- Lidar Sensor -->
    <gazebo reference="laser">
        <sensor name='two_d_lidar' type='gpu_lidar'>
            <topic>/scan</topic>
            <update_rate>50</update_rate>
            <ignition_frame_id>laser</ignition_frame_id>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>${-pi}</min_angle>
                        <max_angle>${pi}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>12.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.001</stddev>
                </noise>
            </lidar>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>



</robot>    