# This YAML file defines the transport parameters and flags for each agent.
esp32_base_serial:
  enable: true # Set to false if you want to disable this node
  transport: "serial"
  # port: "/dev/serial/by-path/platform-3610000.usb-usb-0:2.1.3:1.0-port0"
  port: "/dev/ttyUSB0"
  baudrate: "115200"
  verbose_level: "6"

esp32_io_serial:
  enable: true # Set to false to disable this node
  transport: "serial"
  # port: "/dev/serial/by-path/platform-3610000.usb-usb-0:2.1.2:1.0-port0"
  port: "/dev/ttyUSB1"
  baudrate: "115200"
  verbose_level: "6"

esp32_udp:
  enable: false # Set to true to enable UDP transport and disable serial nodes if desired.
  transport: "udp4"
  port: "8888"
  verbose_level: "4"
